### ISSUE TITLE
Crop circle is not visible as you shown in the Readme.md file

### ISSUE THREAD

**Issue by HKTareen** [gliheng/image_cropper_view#1]
i am unable to crop image by myself it cannot shoe the crop circle or crop rectangular 
Flutter sdk 2.8.1 Flutter Web 

<img width="497" alt="Screenshot 2022-04-18 at 2 30 52 PM" src="https://user-images.githubusercontent.com/86283535/163788632-56d87285-6990-4b78-ba0a-28e783213882.png">

**Comment by gliheng** [comment]
Did you set `clipShape` option to `ClipShape.circle`?

**Comment by HKTareen** [comment]
yes i did

**Comment by gliheng** [comment]
You're right, it's a web specific issue. I'll look into it.

**Comment by gliheng** [comment]
This is due to flutter web does not support Path.combine so far. Here's the tracking issue: https://github.com/flutter/flutter/issues/44572 
Current solution is to draw a line to denote clipping circle or rect. That's may not beautiful.
